#######################################
#                                     #
# DISCLAIMER                          #
# Test generated by Claude Code       #
#                                     #
#######################################

"""
End-to-end test for the Vector Store API (api.py).

Two ways to run it:

  1. As a readable demo (prints what each step does):
       python "12. Vector Stores/test_api.py"

  2. As an automated test suite (asserts everything works):
       pytest "12. Vector Stores/test_api.py" -v

Why a Flask "test client" instead of `requests`?
------------------------------------------------
`api.py` exposes a Flask `app`. Flask ships with `app.test_client()`, which
lets us call the endpoints *in-process* -- no server to start, no port, no
network. It still exercises the real routing, JSON parsing, status codes and
the real SentenceTransformer model, so it proves the API genuinely works
while staying fast and self-contained.
"""

import json

# Importing api.py runs its top-level code: it builds the Flask `app`,
# downloads/loads the "all-MiniLM-L6-v2" model and creates the global store.
# The first run can take a few seconds while the model is fetched.
from api import app


def make_client():
    """A fresh Flask test client. `client.post(...)` == an HTTP POST."""
    return app.test_client()


def post_json(client, url, payload):
    """Small helper so every call sends/receives JSON the same way."""
    resp = client.post(url, data=json.dumps(payload),
                        content_type="application/json")
    return resp.status_code, resp.get_json()


# A tiny corpus chosen so the words in the *query* do NOT appear in the
# matching document. That is what makes this a real test of *semantic*
# search rather than keyword matching.
DOCUMENTS = [
    {
        "text": "The Golden State Warriors clinched the championship "
                "after a dominant fourth quarter last night.",
        "metadata": {"title": "Finals Recap", "author": "J. Smith",
                      "category": "sports"},
    },
    {
        "text": "The senate approved a sweeping tax reform package "
                "that changes brackets for most households.",
        "metadata": {"title": "Tax Bill Passes", "author": "A. Lopez",
                      "category": "politics"},
    },
    {
        "text": "Astronomers detected a new exoplanet orbiting a "
                "distant red dwarf using the transit method.",
        "metadata": {"title": "New World Found", "author": "R. Kahn",
                      "category": "science"},
    },
]


def test_api_flow():
    """
    Walks the whole API in the order a real client would, asserting at
    each step. Kept as ONE test on purpose: api.py keeps the store,
    `documents` dict and `next_id` as module-level globals, so test order
    matters -- a single linear flow is the honest way to test shared state.
    """
    client = make_client()
    log = print  # so the same code reads nicely in demo mode

    # 1. Empty store: search must short-circuit to [] (api.py guards this
    #    because cos_sim on empty embeddings would crash).
    log("\n[1] Search before any documents exist ...")
    status, body = post_json(client, "/documents/search", {"query": "anything"})
    assert status == 200, status
    assert body == [], body
    log(f"    -> {status} {body}  (correctly empty)")

    # 2. Reject bad metadata (missing the required keys).
    log("\n[2] Create a document with invalid metadata ...")
    status, body = post_json(client, "/documents",
                             {"text": "x", "metadata": {"title": "only one"}})
    assert status == 400, (status, body)
    log(f"    -> {status} {body['error']}  (correctly rejected)")

    # 3. Create the real documents.
    log("\n[3] Create the 3 valid documents ...")
    ids = []
    for art in DOCUMENTS:
        status, body = post_json(client, "/documents", art)
        assert status == 201, (status, body)
        ids.append(body["id"])
        log(f"    -> created id={body['id']}  ({art['metadata']['category']})")

    # 4. Fetch one back by id, and prove 404 works for a missing id.
    log("\n[4] GET a document by id ...")
    resp = client.get(f"/documents/{ids[0]}")
    assert resp.status_code == 200
    fetched = resp.get_json()
    assert fetched["id"] == ids[0]
    assert fetched["text"] == DOCUMENTS[0]["text"]
    log(f"    -> {resp.status_code} title='{fetched['metadata']['title']}'")

    resp = client.get("/documents/999999")
    assert resp.status_code == 404
    log(f"    -> GET /documents/999999 = {resp.status_code} (correctly not found)")

    # 5. THE KEY TEST: semantic search.
    #    Query words ("NBA finals result") are absent from every document,
    #    yet the sports document must come back on top. If this passes, the
    #    embedding model + cosine ranking are genuinely working.
    log("\n[5] Semantic search: query shares NO words with the answer ...")
    status, body = post_json(client, "/documents/search",
                             {"query": "who won the NBA finals game",
                              "top_k": 3})
    assert status == 200, (status, body)
    assert len(body) > 0, "expected results"
    top = body[0]
    log(f"    -> top hit: '{top['text'][:55]}...'")
    log(f"       similarity={top['similarity']}  "
        f"category={top['metadata']['category']}")
    assert top["metadata"]["category"] == "sports", (
        f"semantic search failed: expected the sports document on top, "
        f"got {top['metadata']['category']}")

    # 6. Metadata filter: same query, but force the politics category.
    #    Now the sports document must be excluded entirely.
    log("\n[6] Same query, filtered to category=politics ...")
    status, body = post_json(client, "/documents/search",
                             {"query": "who won the NBA finals game",
                              "metadata_filter": {"category": "politics"}})
    assert status == 200, (status, body)
    assert len(body) >= 1
    assert all(r["metadata"]["category"] == "politics" for r in body), body
    log(f"    -> {len(body)} result(s), all category=politics (filter works)")

    log("\nAll checks passed. The API works end to end.\n")


if __name__ == "__main__":
    # Demo mode: just run the flow and let the asserts be the safety net.
    test_api_flow()